version: '2'
services:
  node-compose:
    container_name: node-compose
    build: ./node-compose/
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp:admin1234@postgres/todos
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: admin1234